/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.admin;

import communication.communication;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import views.client.ClientOrderDetailsScreen;

/**
 *
 * @author Unknown Account
 */
public class AdminVendorScreen extends javax.swing.JFrame {
    communication dbAccess = new communication();
    int ID = 0;
    int vendorID = 0;
    
    public boolean updateTable() {
        DefaultTableModel tableModel = new DefaultTableModel(
                new Object[]{"ID", "CNPJ", "Razao Social", "Nome Fantasia", "Email", "Telefone", "CEP", "Estado", "Cidade", "Rua", "Numero"}, 0) {
            // Making cells non-editable
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        ArrayList<ArrayList<?>> vendors = dbAccess.collectVendors();
        ArrayList<String> ids = (ArrayList<String>) vendors.get(0);
        ArrayList<String> cnpjs = (ArrayList<String>) vendors.get(1);
        ArrayList<String> razoes = (ArrayList<String>) vendors.get(2);
        ArrayList<String> fantasias = (ArrayList<String>) vendors.get(3);
        ArrayList<String> emails = (ArrayList<String>) vendors.get(4);
        ArrayList<String> telefones = (ArrayList<String>) vendors.get(5);
        ArrayList<String> ceps = (ArrayList<String>) vendors.get(6);
        ArrayList<String> estados = (ArrayList<String>) vendors.get(10);
        ArrayList<String> cidades = (ArrayList<String>) vendors.get(9);
        ArrayList<String> ruas = (ArrayList<String>) vendors.get(7);
        ArrayList<String> numeros = (ArrayList<String>) vendors.get(8);

        // Iterating in reverse order
        for (int i = ids.size() - 1; i >= 0; i--) {
            //String statusPedido = status.get(i) ? "Entregue" : "Pendente";
            String id = ids.get(i);
            String cnpj = cnpjs.get(i);
            String razao = razoes.get(i);
            String fantasia = fantasias.get(i);
            String email = emails.get(i);
            String telefone = telefones.get(i);
            String cep = ceps.get(i);
            String estado = estados.get(i);
            String cidade = cidades.get(i);
            String rua = ruas.get(i);
            String numero = numeros.get(i);
            tableModel.addRow(new Object[]{id, cnpj, razao, fantasia, email, telefone, cep, estado, cidade, rua, numero});
        }

        Table = new JTable(tableModel);
        ScrollPane.setViewportView(Table);

        Table.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) {
                    int linhaSelecionada = Table.getSelectedRow();
                    vendorID = Integer.parseInt(Table.getValueAt(linhaSelecionada, 0).toString());
                    String razao = Table.getValueAt(linhaSelecionada, 2).toString();
                    Name.setText(razao);
                }
            }
        });

        return true;
    }
    
    /**
     * Creates new form AdminVendorScreen
     */
    public AdminVendorScreen(int _ID) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../../media/TrendStyleIcon.png")));
        setLocationRelativeTo(null);
        this.ID = _ID;
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        ButtonBack = new javax.swing.JButton();
        Name = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        ButtonRegister = new javax.swing.JButton();
        ButtonUpdate = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TrendStyle - Admin Vendor");
        setResizable(false);

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setToolTipText("TrendStyle - Admin Configuration");
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonBack.setBorderPainted(false);
        ButtonBack.setContentAreaFilled(false);
        ButtonBack.setMaximumSize(new java.awt.Dimension(50, 50));
        ButtonBack.setMinimumSize(new java.awt.Dimension(50, 50));
        ButtonBack.setPreferredSize(new java.awt.Dimension(50, 50));
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });
        Panel.add(ButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 50, 40));

        Name.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Panel.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 380, 40));

        ScrollPane.setBorder(null);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Table.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TableComponentAdded(evt);
            }
        });
        ScrollPane.setViewportView(Table);

        Panel.add(ScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 118, 840, 320));

        ButtonRegister.setBorderPainted(false);
        ButtonRegister.setContentAreaFilled(false);
        ButtonRegister.setMaximumSize(new java.awt.Dimension(50, 50));
        ButtonRegister.setMinimumSize(new java.awt.Dimension(50, 50));
        ButtonRegister.setPreferredSize(new java.awt.Dimension(50, 50));
        ButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegisterActionPerformed(evt);
            }
        });
        Panel.add(ButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 469, 55, 52));

        ButtonUpdate.setBorderPainted(false);
        ButtonUpdate.setContentAreaFilled(false);
        ButtonUpdate.setMaximumSize(new java.awt.Dimension(50, 50));
        ButtonUpdate.setMinimumSize(new java.awt.Dimension(50, 50));
        ButtonUpdate.setPreferredSize(new java.awt.Dimension(50, 50));
        ButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUpdateActionPerformed(evt);
            }
        });
        Panel.add(ButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 469, 53, 52));

        ButtonDelete.setBorderPainted(false);
        ButtonDelete.setContentAreaFilled(false);
        ButtonDelete.setMaximumSize(new java.awt.Dimension(50, 50));
        ButtonDelete.setMinimumSize(new java.awt.Dimension(50, 50));
        ButtonDelete.setPreferredSize(new java.awt.Dimension(50, 50));
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });
        Panel.add(ButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(843, 469, 53, 51));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/adminVendor.png"))); // NOI18N
        Panel.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        AdminPanel page = new AdminPanel(this.ID);
        page.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void TableComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TableComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TableComponentAdded

    private void ButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegisterActionPerformed
        AdminVendorManagerScreen page = new AdminVendorManagerScreen(this.ID, 0);
        page.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonRegisterActionPerformed

    private void ButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUpdateActionPerformed
        AdminVendorManagerScreen page = new AdminVendorManagerScreen(this.ID, this.vendorID);
        page.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonUpdateActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        int result = JOptionPane.showConfirmDialog(null, 
            "<html><body><p style='width: 200px;'>Você tem certeza que deseja excluir este fornecedor? Esta ação é irreversível.</p></body></html>", 
            "Confirmação de Exclusão", 
            JOptionPane.YES_NO_OPTION);

        if(result == JOptionPane.YES_OPTION) {
            if (dbAccess.deleteVendor(this.vendorID)) {
                JOptionPane.showMessageDialog(null, 
                "<html><body><p style='width: 200px;'>O fornecedor foi excluído com sucesso.</p></body></html>",
                "Exclusão Concluída", 
                JOptionPane.INFORMATION_MESSAGE);
                AdminVendorScreen page = new AdminVendorScreen(this.ID);
                page.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, 
                "<html><body><p style='width: 200px;'>Oops! Algo deu errado durante a exclusão do fornecedor. Por favor, tente novamente.</p></body></html>",
                "Erro na Exclusão", 
                JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminVendorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminVendorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminVendorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminVendorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminVendorScreen(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonRegister;
    private javax.swing.JButton ButtonUpdate;
    private javax.swing.JLabel Name;
    private javax.swing.JPanel Panel;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JTable Table;
    // End of variables declaration//GEN-END:variables
}
