DROP DATABASE IF EXISTS TrendStyle;
CREATE DATABASE TrendStyle;
USE TrendStyle;

CREATE TABLE ADMINISTRADOR (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    usuario VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    CPF VARCHAR(255) NOT NULL UNIQUE,
    nome VARCHAR(255),
    sobrenome VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    telefone VARCHAR(255) UNIQUE
);

CREATE TABLE FORNECEDOR (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CNPJ VARCHAR(255) NOT NULL UNIQUE,
    razaoSocial VARCHAR(255) NOT NULL,
    nomeFantasia VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    telefone VARCHAR(255) UNIQUE,
    CEP VARCHAR(255),
    rua VARCHAR(255),
    numero VARCHAR(255),
    cidade VARCHAR(255),
    estado VARCHAR(255)
);

CREATE TABLE CLIENTE (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    usuario VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    CPF VARCHAR(255) NOT NULL UNIQUE,
    saldo FLOAT,
    nome VARCHAR(255),
    sobrenome VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    telefone VARCHAR(255) UNIQUE,
    CEP VARCHAR(255) NOT NULL,
    rua VARCHAR(255) NOT NULL,
    numero VARCHAR(255) NOT NULL,
    cidade VARCHAR(255) NOT NULL,
    estado VARCHAR(255) NOT NULL
);

CREATE TABLE PRODUTO_TIPO (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao VARCHAR(255)
);

CREATE TABLE PRODUTO (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao VARCHAR(255),
    imagem_url VARCHAR(255),
    valor FLOAT,
    estoque INTEGER NOT NULL,
    creation DATE NOT NULL,
    id_fornecedor INTEGER,
    id_produto_tipo INTEGER NOT NULL,
    FOREIGN KEY(id_fornecedor) REFERENCES FORNECEDOR(ID),
    FOREIGN KEY(id_produto_tipo) REFERENCES PRODUTO_TIPO(ID)
);

CREATE TABLE CARRINHO (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    id_cliente INTEGER NOT NULL UNIQUE,
    FOREIGN KEY(id_cliente) REFERENCES CLIENTE(ID)
);

CREATE TABLE CARRINHO_PRODUTO (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    quantidade INTEGER NOT NULL,
    id_carrinho INTEGER NOT NULL,
    id_produto INTEGER NOT NULL,
    FOREIGN KEY(id_carrinho) REFERENCES CARRINHO(ID),
    FOREIGN KEY(id_produto) REFERENCES PRODUTO(ID)
);

CREATE TABLE DEPOSITO (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    valor FLOAT NOT NULL,
    data_criacao DATE NOT NULL,
    id_cliente INTEGER NOT NULL,
    FOREIGN KEY(id_cliente) REFERENCES CLIENTE(ID)
);

CREATE TABLE PEDIDO (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    valor FLOAT NOT NULL,
    data_criacao DATE NOT NULL,
    entregue BOOLEAN NOT NULL,
    id_cliente INTEGER NOT NULL,
    FOREIGN KEY(id_cliente) REFERENCES CLIENTE(ID)
);

CREATE TABLE PEDIDO_PRODUTO (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    quantidade INTEGER NOT NULL,
    id_pedido INTEGER NOT NULL,
    id_produto INTEGER NOT NULL,
    FOREIGN KEY(id_pedido) REFERENCES PEDIDO(ID),
    FOREIGN KEY(id_produto) REFERENCES PRODUTO(ID)
);