erDiagram
    ADMINISTRATOR {
        INTEGER ID
        VARCHAR usuario
        VARCHAR senha
        VARCHAR CPF
        VARCHAR nome
        VARCHAR sobrenome
        VARCHAR email
        VARCHAR telefone
    }
    VENDOR {
        INTEGER ID
        VARCHAR CNPJ
        VARCHAR RazaoSocial
        VARCHAR NomeFantasia
        VARCHAR email
        VARCHAR telefone
        VARCHAR CEP
        VARCHAR rua
        VARCHAR numero
        VARCHAR Cidade
        VARCHAR Estado
    }
    CLIENT {
        INTEGER ID
        VARCHAR usuario
        VARCHAR senha
        VARCHAR CPF
        FLOAT saldo
        VARCHAR nome
        VARCHAR sobrenome
        VARCHAR email
        VARCHAR telefone
        VARCHAR CEP
        VARCHAR rua
        VARCHAR numero
        VARCHAR cidade
        VARCHAR estado
    }
    PRODUCT_TYPE {
        INTEGER ID
        VARCHAR nome
        VARCHAR descricao
    }
    PRODUCT {
        INTEGER ID
        VARCHAR nome
        VARCHAR descricao
        VARCHAR imagem_url
        FLOAT valor
        INTEGER estoque
        DATE creation
        INTEGER id_vendor
        INTEGER id_product_type
    }
    CART {
        INTEGER ID
        INTEGER id_client
    }
    CART_PRODUCT {
        INTEGER ID
        INTEGER quantidade
        INTEGER id_cart
        INTEGER id_product
    }
    DEPOSIT {
        INTEGER ID
        FLOAT valor
        DATE data
        INTEGER id_client
    }
    ORDER {
        INTEGER ID
        FLOAT valor
        DATE data
        BOOLEAN entregue
        INTEGER id_client
    }
    ORDER_PRODUCT {
        INTEGER ID
        INTEGER quantidade
        INTEGER id_order
        INTEGER id_product
    }

    PRODUCT }|--|| VENDOR : MADE_BY
    PRODUCT }|--|| PRODUCT_TYPE : IS_OF_TYPE
    CART ||--|| CLIENT : BELONGS_TO
    CART_PRODUCT }|--|| CART : IS_IN
    CART_PRODUCT ||--|| PRODUCT : INCLUDES
    DEPOSIT }o--|| CLIENT : MADE_BY
    ORDER }o--|| CLIENT : PLACED_BY
    ORDER_PRODUCT }|--|| ORDER : IS_IN
    ORDER_PRODUCT }o--|| PRODUCT : INCLUDES