graph LR
    splash[SplashScreen] --> home[Home]

    home --> admin[Administrador]
    home --> client[Cliente]
    
    admin --> admin_register[Cadastro]

    admin --> admin_panel[Painel]

    admin_panel --> admin_admin[Administradores]
    admin_panel --> admin_vendor[Fornecedores]
    admin_panel --> admin_products[Produtos]
    admin_panel --> admin_order[Pedidos]
    
    admin_admin --> admin_admin_manage[Registrar/Visualizar/Atualizar/Deletar]
    
    admin_vendor --> admin_vendor_manage[Registrar/Visualizar/Atualizar/Deletar]

    admin_products --> admin_products_manage[Registrar/Visualizar/Atualizar/Deletar]
    
    admin_products --> admin_category[Categoria]
    admin_category --> admin_category_manage[Registrar/Visualizar/Atualizar/Deletar]

    admin_order --> admin_order_manage[Visualizar/Atualizar]
    
    client --> client_register[Cadastro]

    client --> client_menu[Painel]

    client_menu --> client_config[Configurações]
    client_menu --> client_deposit[Depositar]
    client_menu --> client_shop[Shop]
    client_shop --> client_cart[Carrinho]
    client_menu --> client_cart
    client_menu --> client_order[Pedidos]
    client_cart --> client_order
