graph TB
    subgraph Software[TrendStyle]
        splash[Splash Screen] --> home[Home]

        home --> admin[Administrador]
        home --> client[Cliente]

        admin --> admin_login[Login]
        admin --> admin_register[Cadastro]

        admin_login --> admin_panel[Painel]

        admin_panel --> admin_config[Configurações]
        admin_panel --> admin_vendor[Fornecedores]
        admin_panel --> admin_products[Produtos]
        admin_panel --> admin_order[Pedidos]

        admin_vendor --> admin_vendor_manage[Registrar/Visualizar/Atualizar/Deletar]

        admin_products --> admin_products_manage[Registrar/Visualizar/Atualizar/Deletar]

        admin_order --> admin_order_manage[Visualizar/Atualizar]
        
        client --> client_login[Login]
        client --> client_register[Cadastro]

        client_login --> client_menu[Painel]

        client_menu --> client_config[Configurações]
        client_menu --> client_deposit[Depositar]
        client_menu --> client_shop[Shop] --> client_cart
        client_menu --> client_order[Pedidos]
        client_menu --> client_cart[Carrinho]

        client_cart --> client_cart_confirmation[Confirmar Pedido] --> client_order
    end
